export const mock = [
  {
    Name: "Canva",
    Title: "Canva",
    Domain: "canva.com",
    BreachDate: "2019-05-24",
    AddedDate: "2019-08-09T14:24:01Z",
    ModifiedDate: "2019-08-09T14:24:01Z",
    PwnCount: 137272116,
    Description:
      'In May 2019, the graphic design tool website <a href="https://support.canva.com/contact/customer-support/may-24-security-incident-faqs/" target="_blank" rel="noopener">Canva suffered a data breach</a> that impacted 137 million subscribers. The exposed data included email addresses, usernames, names, cities of residence and passwords stored as bcrypt hashes for users not using social logins. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Canva.png",
    DataClasses: [
      "Email addresses",
      "Geographic locations",
      "Names",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Facepunch",
    Title: "Facepunch",
    Domain: "facepunch.com",
    BreachDate: "2016-06-03",
    AddedDate: "2018-10-17T13:15:39Z",
    ModifiedDate: "2018-10-17T13:31:23Z",
    PwnCount: 342913,
    Description:
      'In June 2016, the game development studio <a href="https://facepunch.com/" target="_blank" rel="noopener">Facepunch</a> suffered a data breach that exposed 343k users. The breached data included usernames, email and IP addresses, dates of birth and salted MD5 password hashes. Facepunch advised they were aware of the incident and had notified people at the time. The data was provided to HIBP by whitehat security researcher and data analyst Adam Davies.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Facepunch.png",
    DataClasses: [
      "Dates of birth",
      "Email addresses",
      "IP addresses",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Gravatar",
    Title: "Gravatar",
    Domain: "gravatar.com",
    BreachDate: "2020-10-03",
    AddedDate: "2021-12-05T22:45:58Z",
    ModifiedDate: "2021-12-08T01:47:02Z",
    PwnCount: 113990759,
    Description:
      'In October 2020, <a href="https://www.bleepingcomputer.com/news/security/online-avatar-service-gravatar-allows-mass-collection-of-user-info/" target="_blank" rel="noopener">a security researcher published a technique for scraping large volumes of data from Gravatar, the service for providing globally unique avatars </a>. 167 million names, usernames and MD5 hashes of email addresses used to reference users\' avatars were subsequently scraped and distributed within the hacking community. 114 million of the MD5 hashes were cracked and distributed alongside the source hash, thus disclosing the original email address and accompanying data. Following the impacted email addresses being searchable in HIBP, <a href="https://en.gravatar.com/support/data-privacy" target="_blank" rel="noopener">Gravatar release an FAQ detailing the incident</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Gravatar.png",
    DataClasses: ["Email addresses", "Names", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Jefit",
    Title: "Jefit",
    Domain: "jefit.com",
    BreachDate: "2020-08-11",
    AddedDate: "2021-04-27T23:29:31Z",
    ModifiedDate: "2021-04-27T23:29:31Z",
    PwnCount: 9052457,
    Description:
      'In August 2020, the workout tracking app <a href="https://www.jefit.com/jefit-news-product-updates/jefit-data-incident-public-announcement" target="_blank" rel="noopener">Jefit suffered a data breach</a>. The data was subsequently sold within the hacking community and included over 9 million email and IP addresses, usernames and passwords stored as either vBulletin or argon2 hashes. Several million cracked passwords later appeared in broad circulation.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Jefit.png",
    DataClasses: ["Email addresses", "IP addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "MyFitnessPal",
    Title: "MyFitnessPal",
    Domain: "myfitnesspal.com",
    BreachDate: "2018-02-01",
    AddedDate: "2019-02-21T19:28:46Z",
    ModifiedDate: "2019-02-21T20:00:56Z",
    PwnCount: 143606147,
    Description:
      'In February 2018, the diet and exercise service <a href="https://content.myfitnesspal.com/security-information/FAQ.html" target="_blank" rel="noopener">MyFitnessPal suffered a data breach</a>. The incident exposed 144 million unique email addresses alongside usernames, IP addresses and passwords stored as SHA-1 and bcrypt hashes (the former for earlier accounts, the latter for newer accounts). In 2019, <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">the data appeared listed for sale on a dark web marketplace</a> (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/MyFitnessPal.png",
    DataClasses: ["Email addresses", "IP addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "NexusMods",
    Title: "Nexus Mods",
    Domain: "nexusmods.com",
    BreachDate: "2013-07-22",
    AddedDate: "2016-01-17T17:18:47Z",
    ModifiedDate: "2016-01-17T17:18:47Z",
    PwnCount: 5915013,
    Description:
      'In December 2015, the game modding site Nexus Mods <a href="http://www.nexusmods.com/games/news/12670/" target="_blank" rel="noopener">released a statement notifying users that they had been hacked</a>. They subsequently dated the hack as having occurred in July 2013 although there is evidence to suggest the data was being traded months in advance of that. The breach contained usernames, email addresses and passwords stored as a salted hashes.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/NexusMods.png",
    DataClasses: ["Email addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];
